#!/bin/bash

sudo timedatectl set-timezone Asia/Jakarta

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install git curl zip python3 python3-pip -y

sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/>
sudo apt-get update
apt-cache policy docker-ce
sudo apt-get install docker-ce -y
sudo usermod -aG docker ${USER}
